application: buckybase
version: 2
runtime: python
api_version: 1

handlers:
- url: /system
  static_dir: system
  login: admin

- url: /static
  static_dir: static
  expiration: "1d"

- url: /.*
  script: bucky.py
